namespace FoxTrans.Desktop.Services;

public sealed record DesktopConfigurationSaveResult(
    bool IsSuccess,
    DesktopBootstrapResult? Bootstrap,
    IReadOnlyList<ConfigIssue> Issues,
    string? Error = null,
    string? BackupPath = null);

public sealed class DesktopConfigurationStore
{
    private const string CanonicalHeader =
        "// Generated by FoxTrans Desktop. GUI Save writes canonical JSONC.";

    private readonly string _workingDirectory;
    private readonly IAudioInputDeviceCatalogue _devices;
    private readonly Func<string, string?> _environment;

    public DesktopConfigurationStore(
        string workingDirectory,
        IAudioInputDeviceCatalogue devices,
        Func<string, string?> environment)
    {
        _workingDirectory = Path.GetFullPath(workingDirectory);
        _devices = devices;
        _environment = environment;
    }

    public string ConfigPath =>
        Path.Combine(_workingDirectory, "config.jsonc");

    public string BackupPath => ConfigPath + ".bak";

    public IReadOnlyList<AudioInputDevice> GetAudioInputs() =>
        _devices.GetInputs();

    public DesktopConfigurationSaveResult Validate(FoxTransConfig config)
    {
        ArgumentNullException.ThrowIfNull(config);
        var issues = new List<ConfigIssue>(
            ConfigValidator.Validate(config).Issues);
        ValidateHttpEndpoints(config, issues);
        ValidateOutputs(config, issues);

        if (issues.Count == 0)
        {
            ExecutionPlanResolution resolution =
                ExecutionPlanResolver.Resolve(
                    config,
                    _devices.GetInputs(),
                    _environment);
            issues.AddRange(resolution.Issues);
        }

        return new(
            issues.Count == 0,
            null,
            issues);
    }

    public DesktopConfigurationSaveResult Save(FoxTransConfig config)
    {
        DesktopConfigurationSaveResult validation = Validate(config);
        if (!validation.IsSuccess)
            return validation;

        Directory.CreateDirectory(_workingDirectory);
        string temporary = ConfigPath + ".tmp";
        bool hadExisting = File.Exists(ConfigPath);
        string canonical = CanonicalHeader + Environment.NewLine +
            AppConfig.Serialize(config);

        try
        {
            File.WriteAllText(temporary, canonical);
            FoxTransConfig staged = AppConfig.Read(temporary);
            DesktopConfigurationSaveResult stagedValidation = Validate(staged);
            if (!stagedValidation.IsSuccess)
            {
                TryDeleteTemporary(temporary);
                return stagedValidation;
            }

            if (hadExisting)
                File.Copy(ConfigPath, BackupPath, overwrite: true);

            File.Move(temporary, ConfigPath, overwrite: true);
            DesktopBootstrapResult bootstrap = DesktopBootstrap.Load(
                _workingDirectory,
                _devices,
                _environment);
            if (!bootstrap.IsValid)
            {
                RestoreExistingFile(hadExisting);
                return new(
                    false,
                    null,
                    bootstrap.Issues,
                    "The saved configuration could not be resolved. The previous file was restored.",
                    hadExisting ? BackupPath : null);
            }

            return new(
                true,
                bootstrap,
                [],
                BackupPath: hadExisting ? BackupPath : null);
        }
        catch (Exception exception) when (
            exception is IOException or
            UnauthorizedAccessException or
            ConfigurationException or
            AudioDeviceSelectionException)
        {
            TryDeleteTemporary(temporary);
            RestoreExistingFile(hadExisting);
            return new(
                false,
                null,
                [],
                DiagnosticText.Safe(exception.Message, 800),
                hadExisting && File.Exists(BackupPath) ? BackupPath : null);
        }
    }

    public string BuildSanitizedDiagnostics(
        DesktopBootstrapResult bootstrap,
        string applicationVersion)
    {
        string pipeline = bootstrap.Plan?.PipelineKind.ToString() ??
            "not resolved";
        string issues = bootstrap.Issues.Count == 0
            ? "none"
            : string.Join(
                Environment.NewLine,
                bootstrap.Issues.Select(issue =>
                    $"- {issue.Path}: " +
                    DiagnosticText.Safe(issue.Message, 800)));
        return $"""
            FoxTrans Desktop {applicationVersion}
            Configuration: {bootstrap.ConfigPath}
            Pipeline: {pipeline}
            Valid: {bootstrap.IsValid}
            Issues:
            {issues}
            """;
    }

    private void RestoreExistingFile(bool hadExisting)
    {
        try
        {
            if (hadExisting && File.Exists(BackupPath))
            {
                string restore = ConfigPath + ".restore.tmp";
                File.Copy(BackupPath, restore, overwrite: true);
                File.Move(restore, ConfigPath, overwrite: true);
            }
            else if (!hadExisting && File.Exists(ConfigPath))
            {
                File.Delete(ConfigPath);
            }
        }
        catch
        {
            // The original save error remains the actionable failure.
        }
    }

    private static void ValidateHttpEndpoints(
        FoxTransConfig config,
        List<ConfigIssue> issues)
    {
        PipelineConfig pipeline = config.EffectivePipeline;
        if (pipeline.Speech is OpenAiChatAudioConfig direct)
            ValidateHttpEndpoint(direct.BaseUrl, "pipeline.speech.baseUrl", issues);
        if (pipeline.Speech is OpenAiTranscriptionConfig transcription)
            ValidateHttpEndpoint(
                transcription.BaseUrl,
                "pipeline.speech.baseUrl",
                issues);
        if (pipeline.Speech is VoxtralFoxConfig voxtral)
            ValidateHttpEndpoint(voxtral.BaseUrl, "pipeline.speech.baseUrl", issues);
        if (pipeline.Translation is OpenAiChatConfig translation)
            ValidateHttpEndpoint(
                translation.BaseUrl,
                "pipeline.translation.baseUrl",
                issues);
    }

    private static void ValidateHttpEndpoint(
        string? value,
        string path,
        List<ConfigIssue> issues)
    {
        if (string.IsNullOrWhiteSpace(value))
            return;
        if (!Uri.TryCreate(value, UriKind.Absolute, out Uri? endpoint) ||
            endpoint.Scheme is not ("http" or "https") ||
            string.IsNullOrWhiteSpace(endpoint.Host))
        {
            issues.RemoveAll(issue => issue.Path == path);
            issues.Add(
                new(path, "Endpoint must be an absolute HTTP or HTTPS URL."));
        }
    }

    private static void ValidateOutputs(
        FoxTransConfig config,
        List<ConfigIssue> issues)
    {
        int index = 0;
        foreach (OutputProviderConfig output in config.EffectiveOutputs)
        {
            ConfigIssue? issue = ConfigValidator.ValidateOutput(
                output,
                $"outputs[{index}].address");
            if (issue is not null)
                AddOnce(issues, issue);
            index++;
        }
    }

    private static void AddOnce(
        List<ConfigIssue> issues,
        ConfigIssue issue)
    {
        if (issues.All(existing => existing.Path != issue.Path))
            issues.Add(issue);
    }

    private static void TryDeleteTemporary(string path)
    {
        try
        {
            if (File.Exists(path))
                File.Delete(path);
        }
        catch
        {
        }
    }

}
