<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>FoxTrans.Cli</AssemblyName>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
    <PublishReadyToRun>true</PublishReadyToRun>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <EventSourceSupport>false</EventSourceSupport>
    <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="[0.57.2]" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../FoxTrans/FoxTrans.csproj" />
  </ItemGroup>

</Project>
